### ISSUE TITLE
Bewertung!

### ISSUE THREAD

**Issue by theLeroy** [theLeroy/creativeplatform#2]
@lebalz 
Guten Tag 

Ich habe einen Branch erstellt den sie zum bewerten verwenden können. Alternativ können Sie die Webseite auch auf https://trash.janiswanger.ch/ begutachten.

Branche:
https://github.com/theLeroy/creativeplatform/tree/Bewertung-stand-19.06.19

Grüsse Janis

**Comment by theLeroy** [comment]
@lebalz Konnten Sie das ganze schon anschauen?

**Comment by lebalz** [comment]
@theLeroy Ja, die Mail mit der Bewertung habe ich gestern Abend verschickt.
